--DDL
--CRIAÇÃO BANCO DE DADOS (DB)

CREATE DATABASE SpMedGroup_Tarde;

--UTILIZAR O DB CRIADO
USE SpMedGroup_Tarde;

--CRIAR AS TABELAS DO BANCO DE DADOS
CREATE TABLE StConsulta (
	IdStConsulta INT PRIMARY KEY IDENTITY,
	Situacao VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Especialidade (
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) UNIQUE
);

CREATE TABLE Clinica (
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) NOT NULL UNIQUE,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	RazaoSocial VARCHAR (255) NOT NULL,
	Endereco VARCHAR (255) NOT NULL
);

CREATE TABLE Prontuario (
	IdProntuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) NOT NULL UNIQUE,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (255) NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR (255),
	RG CHAR (14) NOT NULL UNIQUE,
	CPF CHAR (11),
	Endereco VARCHAR (255),
	CEP CHAR (8)
);

CREATE TABLE Administrador (
	IdAdministrador INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) NOT NULL,
	Email VARCHAR (255)NOT NULL UNIQUE,
	Senha VARCHAR (255) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
);

CREATE TABLE Medico (
	IdMedico INT PRIMARY KEY IDENTITY,
	Crm VARCHAR (255)NOT NULL UNIQUE,
	Nome VARCHAR (255) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (255) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade)
);

CREATE TABLE Consulta (
	IdConsulta INT PRIMARY KEY IDENTITY,
	DataConsulta DATETIME DEFAULT GETDATE(),
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico),
	IdStConsulta INT FOREIGN KEY REFERENCES StConsulta(IdStConsulta),
	IdProntuario INT FOREIGN KEY REFERENCES Prontuario(IdProntuario)
);

--ALTERAR DATA TYPE PARA NÃO UNIQUE
ALTER TABLE Prontuario
ALTER COLUMN Nome VARCHAR (255) NOT NULL;